env: eca
model: ./mlx_qwen3_0_6b
ref_model: ""
steps: 100
pairs: 8
width: 32
attempts: 1
reward_mode: acc
seed: 123
soft_prompt: true
samples: 4
eta: 5.0
beta: 0.05
temp: 0.7
top_p: 0.95
log_csv: runs/eca_gspo.csv
adv_norm: softmax
beta_schedule: fixed
target_kl: 0.05
ema_ref_decay: 0.0
